name: Build-test

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies and test app
        run: |
         sudo apt update
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install --upgrade pytest
      
      
      